### ISSUE TITLE
social smells and DV8 cheatsheets

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu_cheatsheet#1]
Adding the Social Smells cheatsheet and DV8 cheatsheet for Kaiaulu.

**Comment by carlosparadis** [comment]
@leilani-reich Thank you!

Would you mind making a separate issue / pull request for your final presentation and poster too for here? I will probably rename the repo to something more general down the road when I figure out git LFS. 

They could go on a /presentation and /poster folder.
