### ISSUE TITLE
capstone final presentation and poster

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu_cheatsheet#3]
Final presentation/poster for ICS496 capstone Software Analytics Insights team.

Will put in  /presentation and /poster folder.

**Comment by leilani-reich** [comment]
@carlosparadis it says this is issue #3 but I only see 2 issues in this repo. Did I miss something?

**Comment by carlosparadis** [comment]
@leilani-reich Issues and Pull Requests share ids. #2 is your PR.

**Comment by leilani-reich** [comment]
oh okay thanks

**Comment by carlosparadis** [comment]
Thank you!
