### ISSUE TITLE
Final PPT, Poster and Cheatsheet for Kaiaulu Fake Data Generators 

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu_cheatsheet#5]

**Comment by Rubegen** [comment]
[ICS 496 Final Presentation.pdf](https://github.com/sailuh/kaiaulu_cheatsheet/files/13495453/ICS.496.Final.Presentation.pdf)
[ICS 496 Final Presentation.pptx](https://github.com/sailuh/kaiaulu_cheatsheet/files/13495455/ICS.496.Final.Presentation.pptx)
